apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-container
        image: 18515481949/backend-image:latest
        env:
        - name: MySqlHost
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MySqlHost
        - name: MySqlPort
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MySqlPort
        - name: MySqlUserName
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MySqlUserName
        - name: MySqlPassword
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MySqlPassword
        - name: MySqlDatabase
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MySqlDatabase
        - name: RedisPort
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: RedisPort
        - name: RedisHost
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: RedisHost
        - name: RedisPassword
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: RedisPassword
        - name: RedisDb
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: RedisDb
        ports:
        - containerPort: 7001
        volumeMounts:
        - name: uploads-volume
          mountPath: /root/egg-charling/public/uploads
      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: uploads-pvc
      nodeSelector:
        mysql-ready: "true"
